name: TaaS Capture

on:
  workflow_dispatch:
    inputs:
      session_hash:
        description: 'SHA256 hash of session file'
        required: true
        type: string
      channel:
        description: 'Channel (IDE, App, API)'
        required: true
        default: 'IDE'
        type: choice
        options:
          - IDE
          - App
          - API
      notes:
        description: 'Optional notes about the session'
        required: false
        type: string

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get next transcript ID
        id: next_id
        run: |
          mkdir -p services/taas/records
          LAST=$(ls services/taas/records/tx*.md 2>/dev/null | sed 's/.*tx0*\([0-9]*\).*/\1/' | sort -n | tail -1)
          NEXT=$((${LAST:-0} + 1))
          NEXT_PADDED=$(printf "%03d" $NEXT)
          echo "id=tx${NEXT_PADDED}" >> $GITHUB_OUTPUT
          echo "Next transcript ID: tx${NEXT_PADDED}"

      - name: Create public transcript reference
        run: |
          DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          DATE_SHORT=$(date -u +%Y%m%d)

          mkdir -p services/taas/records

          cat > services/taas/records/${{ steps.next_id.outputs.id }}-${DATE_SHORT}.md << EOF
          # TRANSCRIPT REFERENCE - ${{ steps.next_id.outputs.id }}

          ---

          ## Metadata

          - Transcript ID: ${{ steps.next_id.outputs.id }}
          - Timestamp: ${DATE}
          - Channel: ${{ inputs.channel }}
          - Hash: sha256:${{ inputs.session_hash }}
          - Status: Referenced

          ---

          ## Notes

          ${{ inputs.notes || 'No notes provided.' }}

          ---

          ## Storage

          Raw content in permanent-local .transcripts/ repository.
          This is a PUBLIC reference only.

          ---
          EOF

      - name: Commit transcript reference
        run: |
          git config user.name "CANONIC Bot"
          git config user.email "bot@canonic.org"
          git add services/taas/records/
          git commit -m "TaaS: ${{ steps.next_id.outputs.id }} referenced (${{ inputs.channel }})"
          git push

      - name: TaaS Summary
        run: |
          echo "## TaaS Capture" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Field | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| ID | ${{ steps.next_id.outputs.id }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Channel | ${{ inputs.channel }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Hash | sha256:${{ inputs.session_hash }} |" >> $GITHUB_STEP_SUMMARY
